filebeat.inputs:  # Reads logs from file system
- type: log
  paths:
  - /Users/Kunal.Agarwala/Documents/Horizon Hello World Challenge/helloworldreader.log

  output.elasticsearch:  #writes to elasticsearch?
   hosts: ["localhost:9200"]