---
- name: Set environment variables for HelloWorldReader
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Insert hello world environment variable using ansible
      #ansible.builtin.lineinfile:
      ansible.builtin.blockinfile:
        
        path: /Users/Kunal.Agarwala/Documents/Horizon Hello World Challenge/helloworld.env
        #regexp: '^TestMessage='
        #line: "TestMessage=Please work"
         block: |
          # Add environment variables here
          TestMessage=Please work
        
    - name: "Echo .env"
      ansible.builtin.debug:
        msg: " {{ lookup('ansible.builtin.file', '/Users/Kunal.Agarwala/Documents/Horizon Hello World Challenge/helloworld.env') }}"