---
- name: Set environment variables for  HelloWorldReader
  hosts: 127.0.0.1                                                
  connection: local
  tasks:
    - name: Insert hello world environment variable using ansible
      ansible.builtin.set_fact:    #built in feature used for representing system properties (fact variables); for environment variables, that's the link
        dest: /Users/Kunal.Agarwala/Documents/Horizon Hello World Challenge/helloworld.env
        line: '{{item.key}}={{item.value}}'
        create: yes
      with_dict:
       NAME: kunal
       MESSAGE: helloworld!
